### ISSUE TITLE
gitflow - built Win64.DLL can't be loaded

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/phoenix-shared-interface#5]
When I pick the built phoenix-shared.dll from GitHub actions, I can't run it neither on PxCs.Tests nor Unity.

The following error appears:
![image](https://user-images.githubusercontent.com/120568393/231773678-38284148-ddc7-4242-8074-4176cd285b86.png)

What I checked:
* When I build phoenix-shared with MinGW-64 on Windows, I include the "libstdc++" as static dependency. This solved this issue earlier.
* I checked file size (first indicator of different static dependencies)
![image](https://user-images.githubusercontent.com/120568393/231774643-cbb36934-f6fd-4be8-b16a-41c106754901.png)
--> libphoenix-shared.dll -> working one built with mingw  
--> phoenix-shared.dll -> taken from GitHub action

* I checked with [DependencyWalker](https://www.dependencywalker.com/) what's the difference between the two dlls.
--> Yes. Both show warnings/errors - seems natural ¯\_(ツ)_/¯
--> the GitHub Action one (second one) shows additional errors about API-MS-WIN-CRT in the main window. Could be related to these missing ones? Are there any required DLLs for Windows? Or can we bake it into the dll itself (like libstdc++ with mingw)

libphoenix-shared.dll
![image](https://user-images.githubusercontent.com/120568393/231775231-2384deba-a3b3-4275-905b-4975d6b20b80.png)

phoenix-shared.dll
![image](https://user-images.githubusercontent.com/120568393/231775372-a63ad94e-5ed1-4840-9059-154e7e88e23a.png)

Feel free to ping me for further tests.

**Comment by lmichaelis** [comment]
Hm it might have something to do with missing VCRedist on your end. That should not be something you have to install though so I'm with you on statically linking MSVC here. But I'm not sure how to do it. I found https://stackoverflow.com/a/55460238 but it doesn't seem to work correctly.

**Comment by Tyroonis** [comment]
I had built the "old" bridge with Windows in MinGW.

Here my Build Workflow:
``` 
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Mingw
      uses: msys2/setup-msys2@v2
      with:
        update: true
        mingw_arch: x86_64

    - name: Build
      run: |
        cmake -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=Release -DPCBRIDGE_BUILD_EXECUTABLE=OFF
        cmake --build build

   - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: .dll
        path: |
          build/libphoenix-csharp-bridge.dll
```
